name: Markdown Link Check

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:  # <-- This allows manual run

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v1.6.1
        with:
          args: >-
            --verbose
            --no-progress
            --accept 200,403
            --exclude-path node_modules
            .
